### ISSUE TITLE
🚀[Feat]: Add 'Back-To-Top' Button 

### ISSUE THREAD

**Issue by AsmitaMishra24** [growupanand/ConvoForm#317] opened 2024-07-05 21:01 UTC
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Feature Description

The addition of a "Back to Top" button on the homepage of our website would enhance user experience by providing a convenient way for users to quickly return to the top of the page after scrolling down. This feature is commonly seen on many websites and has become an expected element for smooth navigation.

### Use Case

NA

### Add ScreenShots

https://github.com/growupanand/ConvoForm/assets/146121869/78e08821-c820-4501-99bb-901b6c291335

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by growupanand** [comment] 2024-07-06 07:01
@AsmitaMishra24 assigned to you.

Duplicate of https://github.com/growupanand/ConvoForm/issues/276

**Closed** 2024-09-09 04:53 UTC
Labels: enhancement, UI, gssoc, level1
